#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../include/gk_control.h"
#include "../include/gk_faults.h"
#include "../include/gk_limits.h"
#include "../include/gk_safety.h"

static int g_failures = 0;

static int float_close(float actual, float expected) {
    float diff = actual - expected;
    if (diff < 0.0f) {
        diff = -diff;
    }
    float scale = expected;
    if (scale < 0.0f) {
        scale = -scale;
    }
    if (scale < 1e-6f) {
        scale = 1.0f;
    }
    float rel = diff / scale;
    return rel <= 1e-5f && diff <= 1e-5f;
}

static void expect_float(const char *name, float actual, float expected) {
    if (!float_close(actual, expected)) {
        fprintf(
            stderr,
            "FAIL %s: got %.8f expected %.8f\n",
            name,
            (double)actual,
            (double)expected
        );
        g_failures++;
    }
}

static gk_limit_layer_t read_layer(
    float speed,
    float motor_a,
    float battery_a,
    float regen_a,
    float power_w,
    float rpm,
    float accel,
    float decel,
    float gradient
) {
    gk_limit_layer_t layer = {
        speed, motor_a, battery_a, regen_a, power_w, rpm, accel, decel, gradient,
    };
    return layer;
}

static void run_limits_case(
    const gk_limit_layer_t *hw,
    const gk_limit_layer_t *vehicle,
    const gk_limit_layer_t *mode,
    const gk_limit_layer_t *profile,
    const gk_derating_factors_t *derating,
    const gk_effective_limits_t *expected
) {
    gk_effective_limits_t actual;
    gk_resolve_limits(hw, vehicle, mode, profile, derating, &actual);
    expect_float("max_speed_mps", actual.max_speed_mps, expected->max_speed_mps);
    expect_float(
        "max_motor_current_a", actual.max_motor_current_a, expected->max_motor_current_a
    );
    expect_float(
        "max_battery_current_a", actual.max_battery_current_a, expected->max_battery_current_a
    );
    expect_float("max_power_w", actual.max_power_w, expected->max_power_w);
}

static void run_detect_case(
    const gk_sensor_inputs_t *inputs,
    const gk_safety_config_t *config,
    int previous_adc,
    uint32_t expected
) {
    gk_detection_state_t detection = {.previous_throttle_adc = previous_adc};
    uint32_t actual = gk_detect_faults(inputs, config, &detection);
    if (actual != expected) {
        fprintf(stderr, "FAIL detect_faults: got 0x%x expected 0x%x\n", actual, expected);
        g_failures++;
    }
}

static void run_safety_case(
    gk_safety_state_t state,
    const gk_safety_inputs_t *inputs,
    const gk_safety_config_t *config,
    gk_safety_timers_t *timers,
    uint32_t latched_in,
    float dt,
    gk_safety_state_t expected_state,
    bool expected_torque
) {
    gk_safety_state_t next_state;
    gk_safety_outputs_t outputs;
    uint32_t latched_out = 0;
    gk_safety_step(
        state,
        inputs,
        config,
        timers,
        latched_in,
        dt,
        &next_state,
        &outputs,
        &latched_out
    );
    if (next_state != expected_state) {
        fprintf(stderr, "FAIL safety state: got %d expected %d\n", next_state, expected_state);
        g_failures++;
    }
    if (outputs.torque_permitted != expected_torque) {
        fprintf(stderr, "FAIL safety torque permitted\n");
        g_failures++;
    }
}

static void run_control_case(
    const gk_control_inputs_t *inputs,
    const gk_effective_limits_t *limits,
    const gk_safety_outputs_t *safety,
    gk_control_state_t *state,
    const gk_control_params_t *params,
    float dt,
    const gk_control_outputs_t *expected
) {
    gk_control_outputs_t actual;
    gk_control_step(inputs, limits, safety, state, params, dt, &actual);
    expect_float(
        "motor_torque_request_nm",
        actual.motor_torque_request_nm,
        expected->motor_torque_request_nm
    );
    expect_float(
        "regen_torque_request_nm", actual.regen_torque_request_nm, expected->regen_torque_request_nm
    );
    expect_float("filtered_throttle", actual.filtered_throttle, expected->filtered_throttle);
    if (actual.traction_limited != expected->traction_limited) {
        fprintf(stderr, "FAIL traction_limited\n");
        g_failures++;
    }
}

/* Generated by tools/generate_golden.py */
#include "golden_cases.inc"

int main(void) {
    run_generated_limits_cases();
    run_generated_safety_cases();
    run_generated_control_cases();
    if (g_failures == 0) {
        printf("golden_runner: all cases passed\n");
        return 0;
    }
    fprintf(stderr, "golden_runner: %d failures\n", g_failures);
    return 1;
}
