#!/usr/bin/env python3
"""Emit compile-time hardware limit ceilings from seed vehicle configs."""

from __future__ import annotations

import json
from pathlib import Path

from gokart.config.schemas.components import BatteryPack, Bms, Motor, MotorController
from gokart.config.store import data_root, load_component, load_vehicle
from gokart.config.validation import hardware_limits_from_components

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "firmware" / "esp32" / "include" / "hard_limits.json"
OUT_HEADER = ROOT / "firmware" / "esp32" / "include" / "hard_limits.h"


def _max_limits(records: list[dict]) -> dict[str, float]:
    keys = [
        "max_speed_mps",
        "max_motor_current_a",
        "max_battery_current_a",
        "max_regen_current_a",
        "max_power_w",
        "max_motor_rpm",
        "max_accel_mps2",
        "max_decel_mps2",
        "max_gradient_rad",
    ]
    merged = {key: 0.0 for key in keys}
    for record in records:
        limits = record["limits"]
        for key in keys:
            value = limits.get(key)
            if value is None:
                continue
            merged[key] = max(merged[key], float(value))
    return merged


def main() -> None:
    root = data_root()
    records = []
    for name, version in (("Scott Kart V1", "V1.0"), ("Scott Kart V2", "V2.0")):
        config = load_vehicle(name, version, root=root)
        motor = load_component("motor", config.motor.component_id, root=root)
        controller = load_component(
            "motor_controller", config.motor_controller.component_id, root=root
        )
        battery = load_component("battery", config.battery.component_id, root=root)
        bms = load_component("bms", config.bms.component_id, root=root)
        assert isinstance(motor, Motor)
        assert isinstance(controller, MotorController)
        assert isinstance(battery, BatteryPack)
        assert isinstance(bms, Bms)
        limits = hardware_limits_from_components(motor, controller, battery, bms)
        records.append(
            {
                "vehicle": name,
                "version": version,
                "limits": limits.model_dump(mode="json"),
            }
        )
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(records, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    ceiling = _max_limits(records)
    header = f"""#ifndef HARD_LIMITS_H
#define HARD_LIMITS_H

/* Auto-generated by tools/generate_hard_limits.py — compile-time ceiling across seed vehicles. */

#define GOKART_HW_MAX_SPEED_MPS {ceiling["max_speed_mps"]:.8f}f
#define GOKART_HW_MAX_MOTOR_CURRENT_A {ceiling["max_motor_current_a"]:.8f}f
#define GOKART_HW_MAX_BATTERY_CURRENT_A {ceiling["max_battery_current_a"]:.8f}f
#define GOKART_HW_MAX_REGEN_CURRENT_A {ceiling["max_regen_current_a"]:.8f}f
#define GOKART_HW_MAX_POWER_W {ceiling["max_power_w"]:.8f}f
#define GOKART_HW_MAX_MOTOR_RPM {ceiling["max_motor_rpm"]:.8f}f
#define GOKART_HW_MAX_ACCEL_MPS2 {ceiling["max_accel_mps2"]:.8f}f
#define GOKART_HW_MAX_DECEL_MPS2 {ceiling["max_decel_mps2"]:.8f}f
#define GOKART_HW_MAX_GRADIENT_RAD {ceiling["max_gradient_rad"]:.8f}f

#endif
"""
    OUT_HEADER.write_text(header, encoding="utf-8")
    print(f"Wrote {OUT_JSON}")
    print(f"Wrote {OUT_HEADER}")


if __name__ == "__main__":
    main()
