"""Safety system enums and shared types."""

from __future__ import annotations

from enum import StrEnum


class SafetyState(StrEnum):
    OFF = "OFF"
    BOOT = "BOOT"
    SELF_TEST = "SELF_TEST"
    READY = "READY"
    ARMED = "ARMED"
    DRIVING = "DRIVING"
    FAULT = "FAULT"
    SAFE_SHUTDOWN = "SAFE_SHUTDOWN"


class ContactorCommand(StrEnum):
    OPEN = "OPEN"
    PRECHARGE = "PRECHARGE"
    CLOSE = "CLOSE"


class FaultSeverity(StrEnum):
    WARNING = "WARNING"
    DERATE = "DERATE"
    FAULT = "FAULT"
    CRITICAL = "CRITICAL"


class FaultId(StrEnum):
    THROTTLE_OUT_OF_RANGE = "THROTTLE_OUT_OF_RANGE"
    THROTTLE_IMPLAUSIBLE = "THROTTLE_IMPLAUSIBLE"
    BRAKE_SENSOR_FAULT = "BRAKE_SENSOR_FAULT"
    THROTTLE_BRAKE_SIMULTANEOUS = "THROTTLE_BRAKE_SIMULTANEOUS"
    WHEEL_SPEED_FAULT = "WHEEL_SPEED_FAULT"
    SENSOR_DISAGREEMENT = "SENSOR_DISAGREEMENT"
    CAN_TIMEOUT = "CAN_TIMEOUT"
    VESC_FAULT = "VESC_FAULT"
    BMS_FAULT = "BMS_FAULT"
    PACK_OVERVOLTAGE = "PACK_OVERVOLTAGE"
    PACK_UNDERVOLTAGE = "PACK_UNDERVOLTAGE"
    CELL_OVERVOLTAGE = "CELL_OVERVOLTAGE"
    CELL_UNDERVOLTAGE = "CELL_UNDERVOLTAGE"
    MOTOR_OVERTEMP_DERATE = "MOTOR_OVERTEMP_DERATE"
    MOTOR_OVERTEMP = "MOTOR_OVERTEMP"
    CONTROLLER_OVERTEMP_DERATE = "CONTROLLER_OVERTEMP_DERATE"
    CONTROLLER_OVERTEMP = "CONTROLLER_OVERTEMP"
    BATTERY_OVERTEMP_DERATE = "BATTERY_OVERTEMP_DERATE"
    BATTERY_OVERTEMP = "BATTERY_OVERTEMP"
    OVERSPEED = "OVERSPEED"
    WATCHDOG_RESET = "WATCHDOG_RESET"
    CONTACTOR_FEEDBACK_MISMATCH = "CONTACTOR_FEEDBACK_MISMATCH"
    PRECHARGE_FAILURE = "PRECHARGE_FAILURE"
